export const ListOfImages = [
  'images/Barbecued Lamb.webp',
  'images/Beef Shawarma Wrap Meal.webp',
  'images/Cheese Pie.webp',
  'images/Chicken Shish Tawook.webp',
  'images/Cucumber & Yoghurt.webp',
  'images/Falafel Wrap Meal.webp',
  'images/Falafel.webp',
  'images/Grill Plate - 1.webp',
  'images/Grill Plate - 2.webp',
  'images/Grill Plate - 3.webp',
  'images/Kabob - Chicken.webp',
  'images/Pie - Fillow.webp',
  'images/Pie - Mohammara.webp',
  'images/Pie - Zaatar.webp',
  'images/Rotisserie Chicken Half.webp',
  'images/Side - Mojaddara.webp',
  'images/Side - Tabboule.webp',
];
